Server/fecture/account hotel manager marge into develop
pw-software-engineering/n-team pull request #114
Opened 2021-04-29 13:16 UTC by cangi75

added server controler srevice and data access to endpoint /hotelInfo

2021-05-01 16:07 UTC, cyaneko commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
Is this even needed if you're not going to call the mock method later?

2021-05-01 16:07 UTC, cyaneko commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
Same as above

2021-05-01 16:07 UTC, cyaneko commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
Same as above

2021-05-01 16:08 UTC, cyaneko commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
Same as above

2021-05-03 19:05 UTC, cangi75 commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
done it

2021-05-03 19:05 UTC, cangi75 commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
done it

2021-05-03 19:05 UTC, cangi75 commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
done it

2021-05-03 19:05 UTC, cangi75 commented on Server-Module/Server.Tests/Services/HotelAccountServiceTest.cs
> +            _dataAccessMock.Setup(x => x.AddHotelInfo(It.IsAny<HotelUpdateInfo>())).Returns(hotelID);
done it

2021-05-06 20:59 UTC, Michalski-Artur requested changes
Server module not building. "The type or namespace name 'Exceptions' does not exist in the namespace 'Server'"

2021-05-09 16:10 UTC, mtabor99-pw approved these changes

2021-05-09 17:03 UTC, cyaneko approved these changes

2021-05-09 17:47 UTC, Michalski-Artur requested changes

2021-05-09 17:47 UTC, Michalski-Artur commented on Server-Module/Server/ViewModels/HotelUpdateInfo.cs
> +        public HotelUpdateInfo(HotelInfoDb hotelInfoDb)
.

2021-05-09 17:47 UTC, Michalski-Artur commented on Server-Module/Server/Services/HotelAccountService/HotelAccountService.cs
> +            return new ServiceResult(System.Net.HttpStatusCode.OK, null);
.

2021-05-09 17:52 UTC, cangi75 commented on Server-Module/Server/Database/DataAccess/HotelAccount/HotelAccountDataAccess.cs
> +            var pic = dbContext.HotelPictures.Find(hotelInfoDb.HotelPictures);
>

2021-05-09 17:52 UTC, cangi75 commented on Server-Module/Server/Database/DataAccess/HotelAccount/HotelAccountDataAccess.cs
> +            var pom = dbContext.HotelPictures.AsEnumerable().Where(x => x.HotelID == hotelId);
?

2021-05-09 17:52 UTC, cangi75 commented on Server-Module/Server/Database/DataAccess/HotelAccount/HotelAccountDataAccess.cs
> +            dbContext.HotelPictures.AddRange(hotelInfoDb.HotelPictures);
?

2021-05-09 17:52 UTC, cangi75 commented on Server-Module/Server/Services/HotelAccountService/HotelAccountService.cs
> +                var h = mapper.Map<HotelInfoDb>(hotelUpdateInfo);
?

2021-05-09 17:52 UTC, cangi75 commented on Server-Module/Server/ViewModels/HotelUpdateInfo.cs
> +        public HotelUpdateInfo(HotelInfoDb hotelInfoDb)
?

2021-05-09 17:53 UTC, cangi75 commented on Server-Module/Server/Services/HotelAccountService/HotelAccountService.cs
> +            return new ServiceResult(System.Net.HttpStatusCode.OK, null);
?

2021-05-09 17:59 UTC, Michalski-Artur commented on Server-Module/Server/Database/DataAccess/HotelAccount/HotelAccountDataAccess.cs
> +            var pic = dbContext.HotelPictures.Find(hotelInfoDb.HotelPictures);
I would like to explain myself from dots (aka ".") tomorrow on discord

2021-05-11 10:23 UTC, Michalski-Artur approved these changes
Some refactoring will be still essential but I will hande it on my own tomorrow

2021-05-11 11:04 UTC, merged