Added Autorization of Hotel in server
pw-software-engineering/n-team pull request #52
Opened 2021-03-30 15:21 UTC by cangi75

2021-03-30 15:26 UTC, cyaneko approved these changes

2021-03-30 19:06 UTC, mtabor99-pw requested changes
1. Change authorization scheme to look at headers not cookies
2. Use the (not yet implemented) interface IHotelCredentialsDataAccess to get hotel ID connected with hotel accss token in x-hotel-token header

2021-03-31 19:33 UTC, daveedoo approved these changes

2021-04-11 12:09 UTC, mtabor99-pw approved these changes

2021-04-11 12:11 UTC, merged