Feature/database interfaces tests
pw-software-engineering/n-team pull request #79
Opened 2021-04-16 16:21 UTC by Michalski-Artur

- [x] Implement integration tests for DataAccess
- [x] Implement unit tests for OfferService

2021-04-16 16:27 UTC, Michalski-Artur commented
Integration tests for DataAccess fail cause database for tests is ran on local sql server

2021-04-17 15:45 UTC, cyaneko commented
I'll let this through for now, but this means we need either a way to deploy and test the database using GitHub Actions, or a remote test database (might happen with CD looming?)

2021-04-17 15:45 UTC, cyaneko approved these changes

2021-04-18 12:05 UTC, Michalski-Artur commented
> I'll let this through for now, but this means we need either a way to deploy and test the database using GitHub Actions (perhaps using SQLite for tests only might be enough?) or a remote test database (might happen with CD looming?)

Honestly speaking I thought you will handle it on your own as you know best GitHub Actions @cyaneko

2021-04-18 12:06 UTC, cyaneko commented
Sure, but we'll need to first know which solution we're going with
CD needs some templates which are not available atm
________________________________
From: Michalski-Artur ***@***.***>
Sent: Sunday, April 18, 2021 2:05:23 PM
To: pw-software-engineering/n-team ***@***.***>
Cc: cyaneko ***@***.***>; Mention ***@***.***>
Subject: Re: [pw-software-engineering/n-team] Feature/database interfaces tests (#79)


I'll let this through for now, but this means we need either a way to deploy and test the database using GitHub Actions (perhaps using SQLite for tests only might be enough?) or a remote test database (might happen with CD looming?)

Honestly speaking I thought you will handle it on your own as you know best GitHub Actions @cyaneko<https://github.com/cyaneko>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/pw-software-engineering/n-team/pull/79#issuecomment-821981117>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJ4AILVHGAXCITI2D55YILDTJLDIHANCNFSM43B2SKZA>.

2021-04-19 08:52 UTC, mtabor99-pw approved these changes

2021-04-19 18:59 UTC, daveedoo requested changes
Could you please elaborate what is your idea behind tests naming? If you had any special in mind.
I mean, I don't clearly understand why every test method starts with `Can_`.
I ask because it'd be good to have one common convention across the project.

2021-04-19 19:44 UTC, mtabor99-pw commented on Server-Module/Server.Tests/Services/OfferServiceTest.cs
> +            _offerService = new OfferService(_dataAccessMock.Object, _mapper);
Well, I for one think that naming private class members with an underscore at the beginning is helpful when it comes to differentiating between a local variable and a private class member - especially when method definition is long. Besides it helps when intellisense "filters" all private variables when you type an underscore.

2021-04-20 12:01 UTC, Michalski-Artur commented
I altered some things due to your suggestions @daveedoo
- Change DataAccess to OfferDataAccess 
- Change tests name convention
- Add IDisposable
- Anonymous type creation is seperated into seperate lines
If you would be so kind to take a glance :)

2021-04-20 12:05 UTC, Michalski-Artur commented
Tests naming convention:
- if any additional conditions are not present (ex. happy path): `[function_name]_[expected_behaviour]`
- if any additional conditions are present: `[function_name]_[additional_conditions]_[expected_behaviour]`

2021-04-20 12:11 UTC, daveedoo approved these changes
cool

2021-04-20 12:52 UTC, merged