Feature: Client authorization and authentication
pw-software-engineering/n-team pull request #90
Opened 2021-04-22 14:57 UTC by mtabor99-pw

Implemented epic #6 - client authentication and authorization in client and server modules (with tests)

2021-04-22 16:56 UTC, cangi75 commented on Server-Module/Server/Services/Client/IClientService.cs
> +    }
po co to?

2021-04-22 18:05 UTC, daveedoo commented on Client-Module/Client-Module/Controllers/ClientController.cs
>              {
I suggest using [HttpResponseMessage.EnsureSuccessStatusCode()](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode?view=net-5.0) method. You won't have to think whether this endpoint returns e.g. 200 or 201.

2021-04-22 18:09 UTC, cangi75 commented on Client-Module/Client-Module/Authentication/ClientInfoAccessor.cs
> +            httpRequest.RequestUri = new Uri(ServerApiConfig.BaseUrl + "/client");
This can be moved to creation to IHttpClientFactory

2021-04-22 18:15 UTC, cangi75 commented on Client-Module/Client-Module/Authentication/ClientInfoAccessor.cs
> +            httpRequest.Method = new HttpMethod("GET");
There is funcion GetAsync in HttpClient. I think GetAsync is more readable

2021-04-26 14:06 UTC, cyaneko requested changes
There's a merge conflict in CI; just use changes from the other branch

2021-04-27 12:58 UTC, mtabor99-pw commented on Server-Module/Server/Services/Client/IClientService.cs
> +    }
Removed the interface.

2021-04-27 12:58 UTC, mtabor99-pw commented on Client-Module/Client-Module/Authentication/ServerApiConfig.cs
> +        public static string BaseUrl { get; set; } = "https://localhost:5001/api";
Changed to `/api-client/`

2021-04-27 13:00 UTC, mtabor99-pw commented on Client-Module/Client-Module/Authentication/ClientInfoAccessor.cs
> +            httpRequest.RequestUri = new Uri(ServerApiConfig.BaseUrl + "/client");
Rejected due to some complacations with default URI and relative URI set in HttpRequestMessage (but I will look more into this in the next sprint)

2021-04-27 13:01 UTC, mtabor99-pw commented on Client-Module/Client-Module/Authentication/ClientInfoAccessor.cs
> +            httpRequest.Method = new HttpMethod("GET");
Rejected due to the fact that GetAsync cannot add new headers in HTTP requests.

2021-04-27 13:02 UTC, mtabor99-pw commented on Client-Module/Client-Module/Controllers/ClientController.cs
>              {
Changed to HttpResponseMessage.IsSuccessStatusCode

2021-04-27 13:08 UTC, daveedoo approved these changes

2021-04-27 13:18 UTC, cangi75 approved these changes

2021-04-27 14:16 UTC, merged